name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-demo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build Demo Image
        run: ./gradlew clean buildDemo

  build-azure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build Azure Image
        run: ./gradlew clean buildAzure

  build-nifi-processor:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - name: Build NAR file
        run: ./gradlew nar

      #      - name: Push to GitHub Packages
      #        uses: docker/build-push-action@v1
      #        with:
      #          path: external/nifi
      #          username: ${{ github.actor }}
      #          password: ${{ secrets.GITHUB_TOKEN }}
      #          registry: docker.pkg.github.com
      #          repository: microsoft/data-appliance-gx/nifi
      #          tag_with_ref: false
      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: external/nifi
          pull: true
          push: true
          #          cache-from: type=registry,ref=microsoft/data-appliance-gx/nifi:latest
          cache-to: type=inline
          tags: ghcr.io/microsoft/data-appliance-gx/nifi:latest